# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c629aa4e869d650bc3a8ff4e87ffe071"
name = "testing"
application_url = "https://divorce-checks-journalist-scuba.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_draft_orders,write_products"

[auth]
redirect_urls = [
  "https://divorce-checks-journalist-scuba.trycloudflare.com/auth/callback",
  "https://divorce-checks-journalist-scuba.trycloudflare.com/api/auth"
]

[app_proxy]
url = "https://divorce-checks-journalist-scuba.trycloudflare.com"
subpath = "configurator-api"
prefix = "apps"
