api_version = "2024-10"


[[extensions]]
name = "t:name"
handle = "cart-transformer"

uid = "880efb62-6c5e-ad93-d249-9913aad3d9cb8bb0dbab"

type = "function"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = "echo Done"

  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
